[package]
name = "rome_preprocessing"
version = "0.1.0"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shapefile = "0.2.0"
geo = "0.14.2"
rayon = "1.4.0"
